plugins {
    // 在 Gradle 中提供 Java 支持，搭建编译、构建和测试应用的任务
    id 'java'
    // 在 Gradle 中提供 Spring Boot 支持并声明想要使用哪个版本
    id 'org.springframework.boot' version '2.7.18'
    // 提供对 Spring 的依赖管理特性
    id 'io.spring.dependency-management' version '1.0.15.RELEASE'
}

// Catalog Service 项目的 group ID
group = 'com.polarbookshop'
// 应用的版本，默认为 0.0.1-SNAPSHOT
version = '0.0.1-SNAPSHOT'
// 构建项目所使用的 Java 版本
sourceCompatibility = '17'

// 搜索依赖的制品仓库
repositories {
    mavenCentral()
}

ext {
    set('springCloudVersion', "2021.0.3")
    set('testcontainersVersion', "1.17.3")
}

// 配置 Gradle 以在构建项目的时候使用注解处理器
configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

// 应用使用的依赖
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    // 添加对 Java Bean Validation 的依赖
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    implementation 'org.springframework.retry:spring-retry'
    implementation 'org.flywaydb:flyway-core'

    runtimeOnly 'org.postgresql:postgresql'
    annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    // 为 Spring Reactive Web 添加测试依赖
    testImplementation 'org.springframework.boot:spring-boot-starter-webflux'
    testImplementation 'org.testcontainers:postgresql'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
        mavenBom "org.testcontainers:testcontainers-bom:${testcontainersVersion}"
    }
}

// 为开发环境定义激活的 profile
bootRun {
    systemProperty 'spring.profiles.active', 'testdata'
}

bootBuildImage {
    imageName = "${project.name}"
    environment = ["BP_JVM_VERSION": "17.*"]

    docker {
        publishRegistry {
            username = project.findProperty("registryUsername")
            password = project.findProperty("registryToken")
            url = project.findProperty("registryUrl")
        }
    }
}

// 使用 JUnit5 提供的 JUnit Platform 来启用测试
tasks.named('test') {
    useJUnitPlatform()
}
