server:
  # Web 服务器端口
  port: 9001
  shutdown: graceful
  tomcat:
    # Tomcat 从接收到一个来自客户端的 TCP 连接到实际接收到 HTTP 请求所能等待的时间限制
    connection-timeout: 2s
    # 等待新的 HTTP 请求时连接保持打开状态的时长
    keep-alive-timeout: 15s
    threads:
      # 请求处理线程的最大数量
      max: 50
      # 保持始终运行的最小线程数量
      min-spare: 5

spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1

management:
  endpoints:
    web:
      exposure:
        include: refresh

# 为自定义属性定义值
polar:
  greeting: Welcome to the local book catalog!
